apiVersion: v1
kind: Service
metadata:
  name: mts-auth-ndport
spec:
  type: NodePort
  selector:
    app: mts-auth
  ports:
    - name: http-port
      protocol: TCP
      port: 8080
      nodePort: 30010